#config.yml

Enable Plugin: true

#lobby items
Friends: true
Party: true
Locker: true
Minigame Selector: true

#ranks

Ranks: true
Default: default

Default => "GRAY"
Plus => "GREEN"
YouTube => "DARK_RED"
Helper => "DARK_AQUA"
Moderator => "YELLOW"
HIVE => "GOLD"
Hive++ => "LIGHT_PURPLE"
VIP => "DARK_PURPLE"

#combo

Hive PvP: true
#if false will be regular vanilla pvp

#friends

UI: true
Enabled: true
Friend Limit: true
#there will be a friend limit
Friend Extend with Hive+: true
#there will be more friend slots with hive+ rank
Requests: true
#you can send friend requests
Requests count as slots: true
Friend Req Lasting Time: -1
#-1 for unlimited
Slot Limit: 100
#how many friends you ca have, -1 for unlimited
Slot limit for staff: -1 
#1 for unlimited
Show Avatar in list: true
#will it show their avatar in list
Show Game from list: true
#will it show what game they are in list
Show hub title in list: true
#will it show their hub title in list
New Friend Notifs: true
#if false they will be in toggles
Join Game from list: true
#can you join your friends game from a list

#texture-pack

Joining HIVE Screen Enabled: false
Joining Screen Text: EVO
Photos: true
Force-Join: true

#ui

Old-UI: false
New-UI: true

#parties

UI: true
Invites: true
Invites only from friends: false
YouTube cannot get invite without friend: true
#you can only invite a YouTube Rank if they are in your friends list
Party Slots: 4
#-1 for unlimited 
TP to game with party: true
Can't queue in party: true
TP to custom server with party: false
Party Slots with Hive+: 8
Party Slots with Staff and YT: 12

#locker

UI: true
Hub Titles: enabled
Avatars: enabled
Costumes: enabled
All: false
#all are automatically unlocked
Staff and YT all: true
#staff and YouTube Rank get all unlocked
3D Costumes: true
Minigame Locker button: false

#pets

UI: true
All: false
Staff and YT all: true
Free Rename: true
Unallowed Names:
 - Shit
 - fuck
 - ass
 - Hive
Cubee: true
Endolotl: true
Dragon: true
Rock: true
Pirate Ship: true

#economy
Money: true
Default money: 1000
Pet Price: 10000
Staff and YT get unlimited: true
Money Commands:
 - addmoney
 - givemoney 
 - takemoney
 - setmoney 
 - seemoney
Monetary Symbol: $

#hubtitles
Hub Titles: true

Hub Title Command: /addht

Hub Title Locker Command: /ht

#dora-the-explorer
Dora The Explorer Location: "0, 0, 0"
World: world

#hardcore-parkour
Hardcore Parkour Location: "0, 50, 60"
World: world

#equip
Auto Equip: true

#hub title model
Default: true
#to make your own add to resource pack
#default is a bee

Hub Title Sound Claim: note.pling
Hub Title Particles: rainbow.swirls

#motd

Force-MOTD: true
Auto: false
MOTD: "§l§eEVO §5Minigames"

#npcs
npc: true
3D Models: true

Skywars: true
Mixed Arcade: true
Deathrun: true
Murder Mystery: true
Treasure Wars: true
TheBridge: true
Survival Games: true
Just Build: true
Hide and seek: true

#positions

World: world

Skywars: "0, 0, 0"
Treasure Wars: "0, 0, 1"
Mixed Arcade: "1, 0, 1"
Deathrun: "2, 0, 1"
Murder Mystery: "3, 0, 1"
TheBridge: "3, 0, 2"
Survival Games: "3, 0, 3"
Just Build: "4, 0, 3"
Hide and Seek: "5, 0, 3"

#particles

enabled: true

Skywars: blue.sparkles
Mixed Arcade: rainbow.sparkles
Deathrun: black.sparkles
Murder Mystery: red.sparkles
Treasure Wars: yellow.sparkles
TheBridge: aqua.sparkles
Survival Games: green.sparkles
Just Build: pink.sparkles
Hide and seek: lime.sparkles

#knockback and cooldown

Cooldown: true
Cooldown: 1s

Knockback: true
Knockback: 1

#quests

Quests: True
NPC: 3, 0, 0 "world"
Model: default 
Name: "§l§eQUESTS \n Click Me!"

Minigame Quests: true
Chatting Quests: false
Exploration Quests: false

Max Quest: 10
Max Quest+: 20
Max Quest YT: 30
Max Quest Staff: 50

Max Quest Period: 10h

#quest-island-models
Quest Back Home: 3, 0, 0 "world"
Quests NPC: 4, 0, 0 "world"

Reward 1: 5, 0, 0 "world"
Reward 2: 10, 0, 0 "world"
Reward 3: 10, 10, 0 "world"

#pets

Cubee: true
Endolotl: true
Dragon: true
Pirate Ship: true
Dragon Colors:
- Blue
- Red
- Green
- Purple
Pirate Ship: true
Rock: true

#mounts

PirateShip: true
Car: true

#minigame-core
Enabled: true

Items:
 Locker: true
 Leave: true
 Friends: true
 Party: true
 Global Locker: true
 Map Vote: true
 
Countdown: 30s
Clear Inv on arena join: true
Clear Inv on lobby join: true
Clear effects on arena join: true
Clear effects on lobby join: true

#levels
levels: true
max level: true

Skywars: 75
Hub: 25
Treasure Wars: 100
TW Prestige: 5
Deathrun: 40
Murder Mystery: 100
Just Build: 20
Mixed Arcade: 25
Hide and Seek: 50
TheBridge: 25

Unlocks: true
Seperate Minigame Locker: true

All: false
Staff and YT all: true

Xp Bar: true
UI: true

#commands

Give XP: /givexp
Take XP: /takexp
See XP: /seexp

#all unlocks are already in if you would like to add more you can do it like this
Add:
  Skywars: 
   76: "Kill Phrase:'{killer} smashed {victim} to pieces.'"
   77: "Gravestone:'gravestone.json'" #you must add the texture
  
 #setup-ui
 Setup UI: true
 Command: /setup ui {minigame}

#shop

Weekly Costumes: true

Display 1: 4, 0, 0 "world"
Display 2: 12, 0, 0 "world"

Money: Economy
Cost: 200

Anime Teens Display: 50, 0, 0 "world"
Pets Board: 25, 0, 0 "world"
Survival World Display: 39, 0, 0 "world"
   
 #minigames
 
 #if you are here, edit all minigames in their respective yml files

SkyWars: true
Hide and Seek: true
Treasure Wars: true
Murder Mystery: true 
Survival Games: true
Just Build: true
Mixed Arcade: true


#not all minigames are complete
...
